USE [master]
GO

/****** Object:  Database [testtabledemo]    Script Date: 18/05/2017 5:59:52 PM ******/
CREATE DATABASE [testtabledemo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'testtabledemo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS01\MSSQL\DATA\testtabledemo.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'testtabledemo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS01\MSSQL\DATA\testtabledemo_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [testtabledemo] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [testtabledemo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [testtabledemo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [testtabledemo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [testtabledemo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [testtabledemo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [testtabledemo] SET ARITHABORT OFF 
GO

ALTER DATABASE [testtabledemo] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [testtabledemo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [testtabledemo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [testtabledemo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [testtabledemo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [testtabledemo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [testtabledemo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [testtabledemo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [testtabledemo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [testtabledemo] SET  ENABLE_BROKER 
GO

ALTER DATABASE [testtabledemo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [testtabledemo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [testtabledemo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [testtabledemo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [testtabledemo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [testtabledemo] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [testtabledemo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [testtabledemo] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [testtabledemo] SET  MULTI_USER 
GO

ALTER DATABASE [testtabledemo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [testtabledemo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [testtabledemo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [testtabledemo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [testtabledemo] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [testtabledemo] SET QUERY_STORE = OFF
GO

USE [testtabledemo]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [testtabledemo] SET  READ_WRITE 
GO


