//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace updatetabledemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItemDetail
    {
        public int Id { get; set; }
        public string UserID { get; set; }
        public string ItemName { get; set; }
        public string Description { get; set; }
        public int Quantity { get; set; }
        public int Price { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
