//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace updatetabledemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTotalMoneySpent
    {
        public int Id { get; set; }
        public string Seller_UserID { get; set; }
        public string Buyer_UserID { get; set; }
        public int Total_Spent { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
